package com.rentflow.payment.controller;

import com.rentflow.payment.dto.PaymentConfirmationRequest;
import com.rentflow.payment.dto.PaymentCreateRequest;
import com.rentflow.payment.dto.PaymentSimulationRequest;
import com.rentflow.payment.dto.PaymentResponse;
import com.rentflow.payment.service.PaymentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/payments")
@RequiredArgsConstructor
@Tag(
        name = "Payment",
        description = "Rent Payment Management APIs"
)
public class PaymentController {

    /*
     * Payment service handles:
     *
     * 1. Manual Owner/Manager payments
     * 2. Simulated Tenant payments
     * 3. Payment confirmation
     * 4. RentCycle amount/status updates
     */
    private final PaymentService paymentService;

    /*
     * ---------------------------------------------------------
     * MANUAL PAYMENT
     * ---------------------------------------------------------
     *
     * Owner/Manager can directly record a verified
     * cash/UPI payment.
     */
    @Operation(
            summary = "Record a new payment"
    )
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public PaymentResponse createPayment(
            @Valid @RequestBody PaymentCreateRequest request) {

        return paymentService.createPayment(request);
    }

    /*
     * ---------------------------------------------------------
     * SIMULATED TENANT PAYMENT
     * ---------------------------------------------------------
     *
     * Tenant uses this for our development/demo payment flow.
     *
     * Payment is created as PENDING.
     * A transaction reference is generated by the backend.
     *
     * It does NOT mark the RentCycle as paid.
     */
    @Operation(
            summary = "Simulate a tenant payment"
    )
    @PostMapping("/simulate")
    @ResponseStatus(HttpStatus.CREATED)
    public PaymentResponse simulatePayment(
            @Valid @RequestBody PaymentSimulationRequest request) {

        return paymentService.simulatePayment(request);
    }

    /*
     * ---------------------------------------------------------
     * GET ALL PAYMENTS
     * ---------------------------------------------------------
     */
    @Operation(
            summary = "Get all payments"
    )
    @GetMapping
    public List<PaymentResponse> getAllPayments() {

        return paymentService.getAllPayments();
    }

    /*
     * ---------------------------------------------------------
     * GET PAYMENT BY ID
     * ---------------------------------------------------------
     */
    @Operation(
            summary = "Get payment by ID"
    )
    @GetMapping("/{id}")
    public PaymentResponse getPaymentById(
            @PathVariable UUID id) {

        return paymentService.getPaymentById(id);
    }

    /*
     * ---------------------------------------------------------
     * GET PAYMENTS FOR RENT CYCLE
     * ---------------------------------------------------------
     */
    @Operation(
            summary = "Get payments for a rent cycle"
    )
    @GetMapping("/rent-cycle/{rentCycleId}")
    public List<PaymentResponse> getPaymentsByRentCycle(
            @PathVariable UUID rentCycleId) {

        return paymentService.getPaymentsByRentCycle(
                rentCycleId
        );
    }

    /*
     * ---------------------------------------------------------
     * CONFIRM PAYMENT
     * ---------------------------------------------------------
     *
     * Only Owner/Manager can confirm a pending payment.
     *
     * Confirmation updates the RentCycle:
     *
     * amountPaid
     * balanceDue
     * status
     */
    @Operation(
            summary = "Confirm a pending payment"
    )
    @PostMapping("/{id}/confirm")
    public PaymentResponse confirmPayment(
            @PathVariable UUID id,
            @Valid @RequestBody PaymentConfirmationRequest request) {

        return paymentService.confirmPayment(
                id,
                request
        );
    }
}